// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy67pR2Fz_dzOU1_D9YAyWisQvqbNicqI',
    appId: '1:100967764621:web:38b59dc03df915b4a688c4',
    messagingSenderId: '100967764621',
    projectId: 'election-app-88586',
    authDomain: 'election-app-88586.firebaseapp.com',
    storageBucket: 'election-app-88586.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRrL-soUuHGFi5wanSK7R0lJq4283Cs-Q',
    appId: '1:100967764621:android:58a185a2ad492a33a688c4',
    messagingSenderId: '100967764621',
    projectId: 'election-app-88586',
    storageBucket: 'election-app-88586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5IwGBR9PmgkU2U6Hn2OwGGZy6OtGKTeg',
    appId: '1:100967764621:ios:1fa317de7b234dd1a688c4',
    messagingSenderId: '100967764621',
    projectId: 'election-app-88586',
    storageBucket: 'election-app-88586.appspot.com',
    iosBundleId: 'com.example.localAuthTutorialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5IwGBR9PmgkU2U6Hn2OwGGZy6OtGKTeg',
    appId: '1:100967764621:ios:1fa317de7b234dd1a688c4',
    messagingSenderId: '100967764621',
    projectId: 'election-app-88586',
    storageBucket: 'election-app-88586.appspot.com',
    iosBundleId: 'com.example.localAuthTutorialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy67pR2Fz_dzOU1_D9YAyWisQvqbNicqI',
    appId: '1:100967764621:web:cf31405935c11310a688c4',
    messagingSenderId: '100967764621',
    projectId: 'election-app-88586',
    authDomain: 'election-app-88586.firebaseapp.com',
    storageBucket: 'election-app-88586.appspot.com',
  );

}